### ISSUE TITLE
Test a command's effect on visible ranges

### ISSUE THREAD

**Issue by brxck** [cursorless-dev/cursorless-vscode#160]
Currently we're storing visible ranges during test case recording, but we are not asserting anything about them. 

This will be interesting because visible ranges depend on the size of the editor, and because the tests will run headlessly in CI.

### To do

- [x] Test folding, esp #401 
- [x] Test scrolling as described in https://github.com/pokey/cursorless-vscode/issues/160#issuecomment-1004807911

**Comment by brxck** [comment]
> [In headless Linux CI machines xvfb is required to run VS Code](https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions)

💭 [xvfb](https://linux.die.net/man/1/xvfb) allows us to specify a screen size...

**Comment by pokey** [comment]
Ooh that's cool @brxck. So sounds like we might be able to do this one more easily on Linux. Then I guess we'd check OS and only check that scrolling happened on Linux, but on all OSes at least check that it didn't break?  Tho one problem is that different screen size might impact navigation map because cursorless only decorates visible ranges. So it might use hats in different places if it's trying to decorate more / less tokens. In current tests all files fit on screen so we don't have that issue. So we might need to get fancier bout navigation map if we impl this one. Eg actually modify it rather than just asserting it matches our expectations. (Which seems to be flakey for some reason anyway at this point 😅)

**Comment by pokey** [comment]
Thinking about this one a bit more, I don't think we need to worry bout screen size.  We can test scrolling as follows.  Have a file like below:

```
hello
there
```

And then say "crown trap".  The "hello" should scroll off the top of the screen, and thus not be part of visible ranges

**Comment by AndreasArvidsson** [comment]
@pokey Should this just be one of unit test or do we want to add is functionality to the test recorder? Your easy examples above would probably work but if we validate them for every single test in the test recorder there is potential for problems of course.
